url: "https://shivikaforpresident.com" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Shivika for President" # the name of your site, e.g. ACME Corp.
sass:
    style: compressed
